# Generated by Django 5.1.1 on 2024-09-08 14:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotelimg',
            field=models.ImageField(default='blank-hotel-picture.png', upload_to='hotelimg'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profileimg'),
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField(default=datetime.datetime.now)),
                ('pnum', models.IntegerField(default=1)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
