# Generated by Django 5.1.1 on 2024-09-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hotel_hotelimg_alter_customuser_profileimg_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(),
        ),
    ]
