# Generated by Django 5.0.6 on 2024-09-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_location_alter_hotel_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='place',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
