# Generated by Django 5.0.6 on 2024-09-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reviewratings'),
        ('core', '0010_hotel_officer'),
    ]

    operations = [
    ]
