# Generated by Django 5.0.6 on 2024-09-13 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_reviewrating_hotel_alter_reviewrating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='hotel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.booked'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
