# Generated by Django 5.0.6 on 2024-09-16 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_reviewrating_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.booked', unique=True),
        ),
    ]
