# Generated by Django 5.0.6 on 2024-09-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_chattable_sender_alter_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='officerTid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booked',
            name='userTid',
            field=models.IntegerField(default=0),
        ),
    ]
